import {createConstants} from './utils';

export const URL_PREFIX = "/api/v1.0/";


export default createConstants(
	'USER_LOGIN_REQUEST',
	'USER_ANY_FAIL',
	'USER_LOGIN_SUCC',
	'USER_GET_SUCC',
	'USER_UPDATE_SUCC',
	'USER_DELETE_SUCC',
	'USER_REGISTER_SUCC',
	'USER_LOGOUT',

	'PROJECTS_FETCH',
	'PROJECTS_FETCH_SUCC',
	'PROJECTS_FETCH_FAIL',
	'PROJECTS_DELETE_SUCC',
	'PROJECTS_UPDATE_SUCC',
	'PROJECTS_CREATE_SUCC',
	'PROJECTS_GET_SUCC',
	'PROJECTS_SET',
	'PROJECTS_UNSET',

	'FORMS_FETCH',
	'FORMS_FETCH_SUCC',
	'FORMS_ANY_FAIL',
	'FORMS_DELETE_SUCC',
	'FORMS_UPDATE_SUCC',
	'FORMS_CREATE_SUCC',
	'FORMS_GET_SUCC',
	'FORMS_SET',
	'FORMS_UNSET',

	'ELEMENTS_FETCH',
	'ELEMENTS_FETCH_SUCC',
	'ELEMENTS_ANY_FAIL',
	'ELEMENTS_DELETE_SUCC',
	'ELEMENTS_UPDATE_SUCC',
	'ELEMENTS_CREATE_SUCC',
	'ELEMENTS_GET_SUCC',
);