//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaaS.Migrations.FaaSContextMigrations.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201610132114141_Initial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201610132114141_Initial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FaaS.FaaS.Migrations.FaaSContextMigrations.Migrations.201610132114141_Initial", typeof(_201610132114141_Initial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1d3W7cuBW+L9B3EHTVFl6Pndx0jZldZMdxYDSJA4+z6J1BS/RYrUTNSpRho+iT9WIfqa9QUqIo/kqUZkaaDowAgS2SHw8PP1LnHPLI//3P7/OfX5LYe4ZZHqVo4Z+fnvkeREEaRmi98Av8+MNf/Z9/+uMf5h/D5MX7ta73ntYjLVG+8J8w3lzMZnnwBBOQnyZRkKV5+ohPgzSZgTCdvTs7+3F2fj6DBMInWJ43vy0QjhJY/kJ+XaYogBtcgPhLGsI4Z89JyapE9b6CBOYbEMCFfwXA6vQjaY4jmJ+Slhi+4Nz3PsQRINKsYPzoewChFANMZL34nsMVzlK0Xm3IAxDfvW4gqfcI4hyyMVw01V2Hc/aODmfWNKyhgiLHadIT8Pw9089MbT5Iyz7XH9FgqapXOupSiwv/YwwTiLDvqX1dLOOM1lN1fAkw+BAEMM+r2TllCCeeVO+E04OwiP478ZZFjIsMLhAscAbiE+9b8RBHwd/g6136 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
